cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove

app_name = 'cart'

urlpatterns = [
  path('', cart_detail, name='cart_detail'),
  path('add/<int:product_id>/', cart_add, name='cart_add'),
  path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path('account/', include('account.urls', namespace='account')),
  path('cart/', include('cart.urls', namespace='cart')),
  path('orders/', include('orders.urls', namespace='orders')),
  path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import order_create

app_name = 'orders'

urlpatterns = [
  path('create/', order_create, name='order_create'),
]

store/urls.py
from django.urls import path
from .views import product_list, product_detail

app_name = 'store'

urlpatterns = [
  path('', product_list, name='product_list'),
  path('<slug:category_slug>/', product_list, name='product_list_by_category'),
  path('<int:id>/<slug:slug>/', product_detail, name='product_detail')
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
  quantity = forms.TypedChoiceField(
    choices=PRODUCT_QUANTITY_CHOICES,
    coerce=int
  )
  override = forms.BooleanField(
    required=False,
    initial=False,
    widget=forms.HiddenInput
  )

cart/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from store.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@login_required
@require_POST
def cart_add(request, product_id):
  cart = Cart(request)
  product = get_object_or_404(Product, id=product_id)
  form = CartAddProductForm(request.POST)
  if form.is_valid():
    cd = form.cleaned_data
    cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
  return redirect('cart:cart_detail')


@login_required
@require_POST
def cart_remove(request, product_id):
  cart = Cart(request)
  product = get_object_or_404(Product, id=product_id)
  cart.remove(product)
  return redirect('cart:cart_detail')


@login_required
def cart_detail(request):
  cart = Cart(request)
  for item in cart:
    item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
  return render(request, 'cart/cart_details.html', {'cart': cart})

templates/cart/cart_details.html
{% extends "layouts/base.html" %}

{% load static %}

{% block content %}

<main class="p-5">
  <div class="md:flex md:items-center md:justify-start">
    <h2 class="text-4xl font-bold tracking-tight text-gray-900 pl-24 pt-5 pb-10">
      Your shopping cart
    </h2>
  </div>
  
  {% with total_items=cart|length %}
    {% if total_items > 0 %}
      
      <div class="mt-3 px-4 sm:px-6 lg:px-8">
        <div class="flow-root">
          <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
              <table class="min-w-full divide-y divide-gray-300">
                <thead class="border-b border-gray-300 text-gray-900">
                  <tr>
                    <th scope="col" class="py-3.5 text-center text-sm font-semibold text-gray-900 sm:pl-0">Image</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Product</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Quantity</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Actions</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Unit price</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Total price</th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-gray-200">
                  
                  {% for item in cart %}
                    {% with product=item.product %}
                      <tr class="border-b border-gray-300">
                        <td class="whitespace-nowrap py-4 text-center text-gray-900 sm:pl-0">
                          <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }} {% else %}{% static 'img/no_image.png' %}{% endif %}" class="object-scale-down h-36 rounded-md m-auto">
                          </a>
                        </td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-900">{{ product.name }}</td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                          <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.override }}
                            <input type="submit" value="Update" class="btn-primary">
                            {% csrf_token %}
                          </form>
                        </td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                          <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                            <input type="submit" value="Remove" class="btn-primary ml-2">
                            {% csrf_token %}
                          </form>
                        </td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">${{ item.price }}</td>
                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">${{ item.total_price }}</td>
                      </tr>
                    {% endwith %}
                  {% endfor %}
                  
                </tbody>
                
                <tfoot>
                  <tr>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0"></th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"></th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"></th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"></th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Total</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">${{ cart.get_total_price }}</th>
                  </tr>
                </tfoot>
                
              </table>
            </div>
          </div>
        </div>
        
        <div class="sm:flex sm:justify-end mt-8 mr-16">
          <div class="mt-4">
            <a href="{% url 'store:product_list' %}" class="btn-outline-primary mr-3">Continue shopping</a>
            <a href="{% url 'orders:order_create' %}" class="btn-primary">Checkout</a>
          </div>
        </div>
      </div>

    {% else %}

      <div class="md:flex md:items-center md:justify-start">
        <div class="pl-24 pt-5 pb-10">
          <div class="border-l-4 border-blue-400 bg-blue-100 p-4">
            <div class="flex">
              <div class="flex-shrink-0">
                <svg class="h-5 w-5 text-blue-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a.75.75 0 000 1.5h.253a.25.25 0 01.244.304l-.459 2.066A1.75 1.75 0 0010.747 15H11a.75.75 0 000-1.5h-.253a.25.25 0 01-.244-.304l.459-2.066A1.75 1.75 0 009.253 9H9z" clip-rule="evenodd" />
                </svg>
              </div>
              <div class="ml-3">
                <p class="text-sm text-blue-700">
                  Your cart is currently empty.
                  <a href="/" class="font-medium text-blue-700 underline hover:text-blue-600">Start shopping.</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

    {% endif %}
  {% endwith %}

</main>

{% endblock content %}