account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
  path('login/', auth_views.LoginView.as_view(), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('register/', views.register, name='register'),
  path('profile/', views.profile, name='profile'),
]

cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove

app_name = 'cart'

urlpatterns = [
  path('', cart_detail, name='cart_detail'),
  path('add/<int:product_id>/', cart_add, name='cart_add'),
  path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path('account/', include('account.urls', namespace='account')),
  path('cart/', include('cart.urls', namespace='cart')),
  path('orders/', include('orders.urls', namespace='orders')),
  path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import order_create

app_name = 'orders'

urlpatterns = [
  path('create/', order_create, name='order_create'),
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from store.models import Product


class Order(models.Model):
  user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
  address = models.CharField(max_length=200)
  city = models.CharField(max_length=200)
  postal_code = models.CharField(max_length=50)
  country = models.CharField(max_length=200)
  date_created = models.DateTimeField(auto_now_add=True)
  date_updated = models.DateTimeField(auto_now=True)
  is_paid = models.BooleanField(default=True)

  def __str__(self):
    return f'Order {self.id}'
  

class OrderItem(models.Model):
  order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
  product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
  price = models.DecimalField(max_digits=10, decimal_places=2)
  quantity = models.PositiveIntegerField(default=1)

  def __str__(self):
    return str(self.id)
  
  def get_cost(self):
    return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
  class Meta:
    model = Order
    fields = ['address', 'city', 'postal_code', 'country']

  def __init__(self, *args, **kwargs):
    self._user = kwargs.pop('user')
    super(OrderCreateForm, self).__init__(*args, **kwargs)

  def save(self, commit=True):
    inst = super(OrderCreateForm, self).save(commit=False)
    inst.user = self._user
    if commit:
      inst.save()
      self.save_m2m()
    return inst

orders/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib.auth import get_user
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


@login_required
def order_create(request):
  cart = Cart(request)
  if request.method == 'POST':
    form = OrderCreateForm(request.POST, user=request.user)
    if form.is_valid():
      order = form.save()
      for item in cart:
        OrderItem.objects.create(order=order, product=item['product'], price=item['price'],quantity=item['quantity'])
      # clear the cart
      cart.clear()
      return render(request, 'order/order_created.html', {'order': order})
  else:
    form = OrderCreateForm(user=request.user)
  return render(request, 'order/create_order.html', {'cart': cart, 'form': form})

templates/order/create_order.html
{% extends "layouts/base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

<main class="p-5">
  <div>
    <div class="mx-auto max-w-2xl px-4 pb-24 sm:px-6 lg:max-w-7xl lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl pt-5">Checkout</h1>
      <div class="mt-12 lg:grid lg:grid-cols-12 lg:items-start lg:gap-x-12 xl:gap-x-16">

        <!-- Shipping address -->
        <section class="lg:col-span-7">
          <form method="post" class="bg-white p-10 rounded-lg">
            <h2 class="text-2xl font-medium text-gray-900 pb-10">Shipping address</h2>
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn-primary py-4 text-lg flex justify-center min-w-0 w-full mb-6">Place order</button>
          </form>
        </section>
        <!-- End Shipping address -->
  
        <!-- Order summary -->
        <section class="mt-16 rounded-lg bg-gray-50 px-4 py-6 sm:p-6 lg:col-span-5 lg:mt-0 lg:p-8">
          <h2 class="text-2xl font-medium text-gray-900">Your order</h2>
          <dl class="mt-6 space-y-4">
            
            {% for item in cart %}
            <div class="flex items-center justify-between">
              <dt class="text-sm text-gray-600">{{ item.quantity }}x {{ item.product.name }}</dt>
              <dd class="text-sm font-medium text-gray-900">${{ item.total_price }}</dd>
            </div>
            {% endfor %}
            
            <div class="flex items-center justify-between border-t border-gray-200 pt-4">
              <dt class="text-base font-medium text-gray-900">Order total</dt>
              <dd class="text-base font-medium text-gray-900">${{ cart.get_total_price }}</dd>
            </div>
          </dl>
        </section>
        <!-- End Order summary -->
        
    </div>
  </div>
</main>

{% endblock content %}

templates/order/order_created.html
{% extends "layouts/base.html" %}

{% block content %}

<main class="p-5">

  <div class="md:flex md:items-center md:justify-start">
    <h2 class="text-4xl font-bold tracking-tight text-gray-900 pl-24 pt-5 pb-10">
      Order created
    </h2>
  </div>

  <div class="md:flex md:items-center md:justify-start">
    <div class="pl-24 pt-5 pb-10">
      <div class="border-l-4 border-blue-400 bg-blue-100 p-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <svg class="h-5 w-5 text-blue-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a.75.75 0 000 1.5h.253a.25.25 0 01.244.304l-.459 2.066A1.75 1.75 0 0010.747 15H11a.75.75 0 000-1.5h-.253a.25.25 0 01-.244-.304l.459-2.066A1.75 1.75 0 009.253 9H9z" clip-rule="evenodd" />
            </svg>
          </div>

          <form action="{% url 'account:login' %}" method="post">
            <div class="ml-3">
              <p class="text-sm text-blue-700">
                <span class="font-medium">Thank you!</span>
                Your order has been successfully placed. The order number is <span class="text-blue-700 font-bold">{{ order.id }}</span>.
                <br>
                <span>Go to your <a href="{% url 'account:profile' %}" class="text-blue-700 font-bold">order history</a>.</span>
              </p>
            </div>
          </form>
          
        </div>
      </div>
    </div>
  </div>

</main>

{% endblock content %}